# Generated by Django 3.2.2 on 2021-06-09 08:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('is_mahasiswa', models.BooleanField(default=False)),
                ('is_adminLab', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KategoriAlat',
            fields=[
                ('id_kategori', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Kategori', models.CharField(max_length=100)),
                ('Keterangan', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorium',
            fields=[
                ('id_labor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ruangan', models.CharField(max_length=100)),
                ('departemen', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateForm',
            fields=[
                ('id_template', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_form', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='uploads/templates/')),
                ('departemenlab', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AdminLab',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('Nama', models.CharField(max_length=20)),
                ('NIP', models.CharField(max_length=12, unique=True)),
                ('LabProdi', models.CharField(max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('Nama', models.CharField(max_length=20)),
                ('NIM', models.CharField(max_length=12, unique=True)),
                ('departemen', models.CharField(max_length=20)),
                ('strata', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Form_Submisi',
            fields=[
                ('id_form', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('judulPenelitian', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=100)),
                ('dosbing', models.CharField(max_length=100)),
                ('date_form', models.DateField()),
                ('date_peminjaman', models.DateField()),
                ('file1', models.FileField(null=True, upload_to='uploads/submisi/')),
                ('file2', models.FileField(null=True, upload_to='uploads/submisi/')),
                ('Verifikasi', models.BooleanField(default=False)),
                ('Status', models.BooleanField(null=True)),
                ('ruangan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratorium')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mahasiswa')),
            ],
        ),
        migrations.CreateModel(
            name='AlatLab',
            fields=[
                ('id_alat', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NamaAlat', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField(default=0)),
                ('gambarAlat', models.FileField(null=True, upload_to='uploads/alat/')),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategorialat')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratorium')),
            ],
        ),
        migrations.CreateModel(
            name='PeminjamanRuangan',
            fields=[
                ('id_peminjaman', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_peminjaman', models.DateField()),
                ('keterangan', models.CharField(max_length=100)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.form_submisi')),
                ('lab_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratorium')),
                ('peminjam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mahasiswa')),
            ],
        ),
    ]
