# Generated by Django 3.2.2 on 2021-06-02 12:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriAlat',
            fields=[
                ('id_kategori', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Kategori', models.CharField(max_length=100)),
                ('Keterangan', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='adminlab',
            name='LabProdi',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='strata',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='departemen',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='AlatLab',
            fields=[
                ('id_alat', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NamaAlat', models.CharField(max_length=100)),
                ('Quantity', models.IntegerField(default=0)),
                ('kategori_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategorialat')),
            ],
        ),
    ]
