# Generated by Django 3.2.4 on 2021-06-14 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210614_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alatlab',
            name='KodeBarang',
        ),
    ]
